/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BbBoatListing {
    'boatId': string;
    'padding': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLBbBoatListingElement extends Components.BbBoatListing, HTMLStencilElement {}
  var HTMLBbBoatListingElement: {
    prototype: HTMLBbBoatListingElement;
    new (): HTMLBbBoatListingElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'bb-boat-listing': HTMLBbBoatListingElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface BbBoatListing {
    'boatId'?: string;
    'padding'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'bb-boat-listing': BbBoatListing;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'bb-boat-listing': LocalJSX.BbBoatListing & JSXBase.HTMLAttributes<HTMLBbBoatListingElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


